import type {
  Shop,
  Category,
  Product,
  Banner,
  Order,
  Driver,
  Promotion,
  CustomerAddress,
} from '@/types';

// ============================================================
// Mock Shop
// ============================================================
export const mockShop: Shop = {
  id: 'shop-001',
  name: 'ชาชัก BKK - Thai Drink House',
  slug: 'cha-chak-bkk',
  logo_url: '/placeholder/shop-logo.jpg',
  cover_url: '/placeholder/shop-cover.jpg',
  address: '88/8 ซอยสุขุมวิท 55 (ทองหล่อ) แขวงคลองตันเหนือ เขตวัฒนา กรุงเทพฯ 10110',
  phone: '02-123-4567',
  opening_hours: {
    monday:    { open: '08:00', close: '21:00', is_open: true },
    tuesday:   { open: '08:00', close: '21:00', is_open: true },
    wednesday: { open: '08:00', close: '21:00', is_open: true },
    thursday:  { open: '08:00', close: '21:00', is_open: true },
    friday:    { open: '08:00', close: '22:00', is_open: true },
    saturday:  { open: '09:00', close: '22:00', is_open: true },
    sunday:    { open: '09:00', close: '20:00', is_open: true },
  },
  delivery_zones: [
    {
      id: 'zone-1',
      name: 'ในรัศมี 3 กม.',
      max_distance_km: 3,
      fee: 0,
    },
    {
      id: 'zone-2',
      name: 'รัศมี 3-5 กม.',
      max_distance_km: 5,
      fee: 20,
      extra_per_km: 10,
    },
    {
      id: 'zone-3',
      name: 'รัศมี 5-10 กม.',
      max_distance_km: 10,
      fee: 40,
      extra_per_km: 15,
    },
  ],
  min_order_amount: 50,
  is_open: true,
  settings: {
    currency: 'THB',
    tax_rate: 0.07,
    accept_cash: true,
    accept_transfer: true,
    accept_promptpay: true,
  },
  scheduling_settings: {
    enabled: true,
    min_advance_minutes: 30,
    max_advance_days: 3,
    slot_interval_minutes: 30,
    max_orders_per_slot: 5,
    blocked_dates: ['2026-04-13', '2026-04-14', '2026-04-15'],
    blocked_weekdays: [],
    blocked_slots: [
      { date: '2026-03-01', slots: ['12:00', '12:30', '13:00'] },
    ],
  },
  order_limits: {
    max_items_per_order: 20,
    max_orders_per_day: 100,
  },
  promptpay_id: '0812345678',
};

// ============================================================
// Shared Product Options (reusable across products)
// ============================================================
const sizeOption = (forCold = true) => ({
  id: 'opt-size',
  name: 'ขนาดแก้ว',
  type: 'single_select' as const,
  is_required: true,
  sort_order: 1,
  choices: [
    { id: 'size-s', name: forCold ? 'S (12 oz.)' : 'S (8 oz.)', price_adjustment: 0, is_available: true },
    { id: 'size-m', name: forCold ? 'M (16 oz.)' : 'M (12 oz.)', price_adjustment: 10, is_available: true },
    { id: 'size-l', name: forCold ? 'L (22 oz.)' : 'L (16 oz.)', price_adjustment: 20, is_available: true },
  ],
});

const sweetnessOption = {
  id: 'opt-sweet',
  name: 'ระดับความหวาน',
  type: 'single_select' as const,
  is_required: true,
  sort_order: 2,
  choices: [
    { id: 'sweet-100', name: 'หวานปกติ (100%)', price_adjustment: 0, is_available: true },
    { id: 'sweet-75', name: 'หวานน้อย (75%)', price_adjustment: 0, is_available: true },
    { id: 'sweet-50', name: 'หวานครึ่ง (50%)', price_adjustment: 0, is_available: true },
    { id: 'sweet-25', name: 'หวานนิดเดียว (25%)', price_adjustment: 0, is_available: true },
    { id: 'sweet-0', name: 'ไม่หวาน (0%)', price_adjustment: 0, is_available: true },
  ],
};

const toppingOption = {
  id: 'opt-topping',
  name: 'ท็อปปิ้ง',
  type: 'multi_select' as const,
  is_required: false,
  sort_order: 3,
  choices: [
    { id: 'top-pearl', name: 'ไข่มุก', price_adjustment: 10, is_available: true },
    { id: 'top-coconut-jelly', name: 'วุ้นมะพร้าว', price_adjustment: 10, is_available: true },
    { id: 'top-grass-jelly', name: 'เฉาก๊วย', price_adjustment: 10, is_available: true },
    { id: 'top-aloe', name: 'ว่านหางจระเข้', price_adjustment: 15, is_available: true },
    { id: 'top-red-bean', name: 'ถั่วแดง', price_adjustment: 10, is_available: true },
    { id: 'top-pudding', name: 'พุดดิ้ง', price_adjustment: 15, is_available: true },
    { id: 'top-whipped-cream', name: 'วิปครีม', price_adjustment: 15, is_available: false },
  ],
};

const milkOption = {
  id: 'opt-milk',
  name: 'ชนิดนม',
  type: 'single_select' as const,
  is_required: false,
  sort_order: 4,
  choices: [
    { id: 'milk-fresh', name: 'นมสด', price_adjustment: 0, is_available: true },
    { id: 'milk-oat', name: 'นมโอ๊ต', price_adjustment: 15, is_available: true },
    { id: 'milk-soy', name: 'นมถั่วเหลือง', price_adjustment: 10, is_available: true },
    { id: 'milk-almond', name: 'นมอัลมอนด์', price_adjustment: 20, is_available: true },
  ],
};

const coffeeStrengthOption = {
  id: 'opt-shot',
  name: 'ความเข้มกาแฟ',
  type: 'single_select' as const,
  is_required: false,
  sort_order: 2,
  choices: [
    { id: 'shot-normal', name: 'ปกติ (1 ช็อต)', price_adjustment: 0, is_available: true },
    { id: 'shot-double', name: 'เข้ม (2 ช็อต)', price_adjustment: 15, is_available: true },
    { id: 'shot-triple', name: 'เข้มมาก (3 ช็อต)', price_adjustment: 25, is_available: true },
  ],
};

// ============================================================
// Mock Categories
// ============================================================
export const mockCategories: Category[] = [
  {
    id: 'cat-cold',
    shop_id: 'shop-001',
    name: 'เครื่องดื่มเย็น',
    icon: '🧊',
    image_url: '/placeholder/category-cold-drinks.jpg',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'cat-hot',
    shop_id: 'shop-001',
    name: 'เครื่องดื่มร้อน',
    icon: '☕',
    image_url: '/placeholder/category-hot-drinks.jpg',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'cat-milk-tea',
    shop_id: 'shop-001',
    name: 'ชานม',
    icon: '🧋',
    image_url: '/placeholder/category-milk-tea.jpg',
    sort_order: 3,
    is_active: true,
  },
  {
    id: 'cat-coffee',
    shop_id: 'shop-001',
    name: 'กาแฟ',
    icon: '☕',
    image_url: '/placeholder/category-coffee.jpg',
    sort_order: 4,
    is_active: true,
  },
  {
    id: 'cat-dessert',
    shop_id: 'shop-001',
    name: 'ของหวาน',
    icon: '🍮',
    image_url: '/placeholder/category-dessert.jpg',
    sort_order: 5,
    is_active: true,
  },
  {
    id: 'cat-bakery',
    shop_id: 'shop-001',
    name: 'เบเกอรี่',
    icon: '🥐',
    image_url: '/placeholder/category-bakery.jpg',
    sort_order: 6,
    is_active: true,
  },
];

// ============================================================
// Mock Products  (15+ items across categories)
// ============================================================
export const mockProducts: Product[] = [
  // ---------- เครื่องดื่มเย็น ----------
  {
    id: 'prod-001',
    shop_id: 'shop-001',
    category_id: 'cat-cold',
    name: 'ชาเขียวมัทฉะเย็น',
    description: 'มัทฉะเกรดพรีเมียมจากอุจิ ชงสดใหม่ทุกแก้ว เสิร์ฟพร้อมน้ำแข็ง',
    price: 55,
    image_url: '/placeholder/matcha-iced.jpg',
    sort_order: 1,
    status: 'available',
    is_recommended: true,
    daily_limit: 50,
    daily_sold: 12,
    max_per_order: 5,
    options: [sizeOption(), sweetnessOption, toppingOption, milkOption],
  },
  {
    id: 'prod-002',
    shop_id: 'shop-001',
    category_id: 'cat-cold',
    name: 'ชาไทยเย็น',
    description: 'ชาไทยสูตรโบราณ หอมกลมกล่อม เข้มข้นรสชาติต้นตำรับ',
    price: 45,
    image_url: '/placeholder/thai-tea-iced.jpg',
    sort_order: 2,
    status: 'available',
    is_recommended: true,
    daily_limit: null,
    daily_sold: 28,
    max_per_order: null,
    options: [sizeOption(), sweetnessOption, toppingOption],
  },
  {
    id: 'prod-003',
    shop_id: 'shop-001',
    category_id: 'cat-cold',
    name: 'น้ำมะม่วงปั่น',
    description: 'มะม่วงน้ำดอกไม้สุกฉ่ำ ปั่นละเอียดกับน้ำแข็ง หวานธรรมชาติ',
    price: 65,
    image_url: '/placeholder/mango-smoothie.jpg',
    sort_order: 3,
    status: 'available',
    is_recommended: false,
    daily_limit: 30,
    daily_sold: 8,
    max_per_order: 3,
    options: [sizeOption(), sweetnessOption],
  },
  {
    id: 'prod-004',
    shop_id: 'shop-001',
    category_id: 'cat-cold',
    name: 'น้ำลำไยสด',
    description: 'ลำไยสดคั้นเอง หวานหอมชื่นใจ เพิ่มเนื้อลำไยเน้น ๆ',
    price: 50,
    image_url: '/placeholder/longan-juice.jpg',
    sort_order: 4,
    status: 'available',
    is_recommended: false,
    daily_limit: null,
    daily_sold: 5,
    max_per_order: null,
    options: [sizeOption(), sweetnessOption],
  },

  // ---------- เครื่องดื่มร้อน ----------
  {
    id: 'prod-005',
    shop_id: 'shop-001',
    category_id: 'cat-hot',
    name: 'ชาไทยร้อน',
    description: 'ชาไทยสูตรดั้งเดิม ชงร้อนหอมกรุ่น ราดนมข้นหวานด้านบน',
    price: 40,
    image_url: '/placeholder/thai-tea-hot.jpg',
    sort_order: 1,
    status: 'available',
    is_recommended: false,
    daily_limit: null,
    daily_sold: 3,
    max_per_order: null,
    options: [sizeOption(false), sweetnessOption],
  },
  {
    id: 'prod-006',
    shop_id: 'shop-001',
    category_id: 'cat-hot',
    name: 'โกโก้ร้อน',
    description: 'โกโก้แท้จากเมล็ดคาเคาคัดพิเศษ ละมุนนุ่มลิ้น',
    price: 55,
    image_url: '/placeholder/hot-cocoa.jpg',
    sort_order: 2,
    status: 'available',
    is_recommended: true,
    daily_limit: null,
    daily_sold: 6,
    max_per_order: null,
    options: [sizeOption(false), sweetnessOption, milkOption],
  },

  // ---------- ชานม ----------
  {
    id: 'prod-007',
    shop_id: 'shop-001',
    category_id: 'cat-milk-tea',
    name: 'ชานมไข่มุก',
    description: 'ชานมสูตรเฉพาะร้าน เสิร์ฟกับไข่มุกนุ่ม ๆ หนึบ ๆ ทำสดใหม่ทุกวัน',
    price: 55,
    image_url: '/placeholder/boba-milk-tea.jpg',
    sort_order: 1,
    status: 'available',
    is_recommended: true,
    daily_limit: 80,
    daily_sold: 35,
    max_per_order: 5,
    options: [sizeOption(), sweetnessOption, toppingOption, milkOption],
  },
  {
    id: 'prod-008',
    shop_id: 'shop-001',
    category_id: 'cat-milk-tea',
    name: 'ชานมบราวน์ชูการ์',
    description: 'ชานมราดซอสน้ำตาลทรายแดงเคี่ยวจนเข้มข้น หอมหวานลึก',
    price: 65,
    image_url: '/placeholder/brown-sugar-milk-tea.jpg',
    sort_order: 2,
    status: 'available',
    is_recommended: true,
    daily_limit: null,
    daily_sold: 18,
    max_per_order: null,
    options: [sizeOption(), sweetnessOption, toppingOption, milkOption],
  },
  {
    id: 'prod-009',
    shop_id: 'shop-001',
    category_id: 'cat-milk-tea',
    name: 'ชานมโอรีโอ',
    description: 'ชานมผสมเกล็ดโอรีโอ ท็อปด้วยวิปครีมและโอรีโอป่น',
    price: 70,
    image_url: '/placeholder/oreo-milk-tea.jpg',
    sort_order: 3,
    status: 'sold_out',
    is_recommended: false,
    daily_limit: 40,
    daily_sold: 40,
    max_per_order: 3,
    options: [sizeOption(), sweetnessOption, toppingOption],
  },

  // ---------- กาแฟ ----------
  {
    id: 'prod-010',
    shop_id: 'shop-001',
    category_id: 'cat-coffee',
    name: 'เอสเปรสโซ่เย็น',
    description: 'เอสเปรสโซ่ช็อตคู่ เมล็ดกาแฟคั่วกลาง อโรมาเข้มกลมกล่อม',
    price: 60,
    image_url: '/placeholder/iced-espresso.jpg',
    sort_order: 1,
    status: 'available',
    is_recommended: false,
    daily_limit: null,
    daily_sold: 14,
    max_per_order: null,
    options: [sizeOption(), sweetnessOption, coffeeStrengthOption, milkOption],
  },
  {
    id: 'prod-011',
    shop_id: 'shop-001',
    category_id: 'cat-coffee',
    name: 'ลาเต้เย็น',
    description: 'เอสเปรสโซ่ผสมนมสดสัดส่วนลงตัว นุ่มละมุนทุกอณู',
    price: 65,
    image_url: '/placeholder/iced-latte.jpg',
    sort_order: 2,
    status: 'available',
    is_recommended: true,
    daily_limit: null,
    daily_sold: 22,
    max_per_order: null,
    options: [sizeOption(), sweetnessOption, coffeeStrengthOption, milkOption, toppingOption],
  },
  {
    id: 'prod-012',
    shop_id: 'shop-001',
    category_id: 'cat-coffee',
    name: 'คาราเมลมัคคิอาโต้',
    description: 'ลาเต้ราดซอสคาราเมลเข้มข้น โปะฟองนมนุ่ม ๆ',
    price: 75,
    image_url: '/placeholder/caramel-macchiato.jpg',
    sort_order: 3,
    status: 'available',
    is_recommended: false,
    daily_limit: 25,
    daily_sold: 10,
    max_per_order: 3,
    options: [sizeOption(), sweetnessOption, coffeeStrengthOption, milkOption],
  },

  // ---------- ของหวาน ----------
  {
    id: 'prod-013',
    shop_id: 'shop-001',
    category_id: 'cat-dessert',
    name: 'บัวลอยไข่หวาน',
    description: 'บัวลอยแป้งเหนียวนุ่มในน้ำกะทิร้อน ๆ หอมใบเตย ใส่ไข่หวาน',
    price: 45,
    image_url: '/placeholder/bua-loy.jpg',
    sort_order: 1,
    status: 'available',
    is_recommended: false,
    daily_limit: 20,
    daily_sold: 7,
    max_per_order: 5,
    options: [],
  },
  {
    id: 'prod-014',
    shop_id: 'shop-001',
    category_id: 'cat-dessert',
    name: 'ข้าวเหนียวมะม่วง',
    description: 'ข้าวเหนียวมูนกะทิ คู่กับมะม่วงน้ำดอกไม้สุกหวาน ราดน้ำกะทิเนื้อแน่น',
    price: 85,
    image_url: '/placeholder/mango-sticky-rice.jpg',
    sort_order: 2,
    status: 'available',
    is_recommended: true,
    daily_limit: 15,
    daily_sold: 11,
    max_per_order: 3,
    options: [],
  },
  {
    id: 'prod-015',
    shop_id: 'shop-001',
    category_id: 'cat-dessert',
    name: 'ทับทิมกรอบ',
    description: 'แห้วเคลือบแป้งมันสีแดง กรอบนอกนุ่มใน ในน้ำกะทิเย็นเฉียบ',
    price: 40,
    image_url: '/placeholder/tub-tim-grob.jpg',
    sort_order: 3,
    status: 'available',
    is_recommended: false,
    daily_limit: null,
    daily_sold: 4,
    max_per_order: null,
    options: [],
  },

  // ---------- เบเกอรี่ ----------
  {
    id: 'prod-016',
    shop_id: 'shop-001',
    category_id: 'cat-bakery',
    name: 'ครัวซองต์เนยสด',
    description: 'ครัวซองต์อบใหม่ กรอบนอกนุ่มใน เนยสดหอมฟุ้ง',
    price: 65,
    image_url: '/placeholder/butter-croissant.jpg',
    sort_order: 1,
    status: 'available',
    is_recommended: false,
    daily_limit: 30,
    daily_sold: 15,
    max_per_order: 5,
    options: [],
  },
  {
    id: 'prod-017',
    shop_id: 'shop-001',
    category_id: 'cat-bakery',
    name: 'เค้กชาไทย',
    description: 'เค้กชิฟฟอนชาไทย สอดไส้ครีมชาไทย ท็อปด้วยครีมสดฟูนุ่ม',
    price: 75,
    image_url: '/placeholder/thai-tea-cake.jpg',
    sort_order: 2,
    status: 'available',
    is_recommended: true,
    daily_limit: 12,
    daily_sold: 8,
    max_per_order: 2,
    options: [],
  },
  {
    id: 'prod-018',
    shop_id: 'shop-001',
    category_id: 'cat-bakery',
    name: 'ขนมปังปิ้งสังขยาใบเตย',
    description: 'ขนมปังปิ้งกรอบ ทาสังขยาใบเตยหอม ๆ หนา ๆ สูตรโบราณ',
    price: 35,
    image_url: '/placeholder/pandan-kaya-toast.jpg',
    sort_order: 3,
    status: 'available',
    is_recommended: false,
    daily_limit: null,
    daily_sold: 9,
    max_per_order: null,
    options: [],
  },
];

// ============================================================
// Mock Banners
// ============================================================
export const mockBanners: Banner[] = [
  {
    id: 'banner-001',
    image_url: '/placeholder/banner-new-matcha.jpg',
    link_url: '/product/prod-001',
    sort_order: 1,
    is_active: true,
  },
  {
    id: 'banner-002',
    image_url: '/placeholder/banner-buy1-get1.jpg',
    link_url: '/promotions',
    sort_order: 2,
    is_active: true,
  },
  {
    id: 'banner-003',
    image_url: '/placeholder/banner-free-delivery.jpg',
    link_url: null,
    sort_order: 3,
    is_active: true,
  },
];

// ============================================================
// Mock Drivers
// ============================================================
export const mockDrivers: Driver[] = [
  {
    id: 'driver-001',
    name: 'สมชาย ใจดี',
    phone: '081-234-5678',
    avatar_url: '/placeholder/driver-somchai.jpg',
    status: 'busy',
    total_deliveries: 1247,
  },
  {
    id: 'driver-002',
    name: 'สุนีย์ รวดเร็ว',
    phone: '089-876-5432',
    avatar_url: '/placeholder/driver-sunee.jpg',
    status: 'available',
    total_deliveries: 863,
  },
];

// ============================================================
// Mock Orders
// ============================================================
export const mockOrders: Order[] = [
  // Order 1 — pending
  {
    id: 'order-001',
    shop_id: 'shop-001',
    customer_id: 'cust-001',
    driver_id: null,
    order_number: 'OD-20260223-001',
    status: 'pending',
    items: [
      {
        id: 'oi-001',
        product_name: 'ชาเขียวมัทฉะเย็น',
        product_image: '/placeholder/matcha-iced.jpg',
        product_price: 55,
        quantity: 2,
        options: [
          { option_id: 'opt-size', option_name: 'ขนาดแก้ว', choice_id: 'size-m', choice_name: 'M (16 oz.)', price_adjustment: 10 },
          { option_id: 'opt-sweet', option_name: 'ระดับความหวาน', choice_id: 'sweet-50', choice_name: 'หวานครึ่ง (50%)', price_adjustment: 0 },
          { option_id: 'opt-topping', option_name: 'ท็อปปิ้ง', choice_id: 'top-pearl', choice_name: 'ไข่มุก', price_adjustment: 10 },
        ],
        item_note: 'เพิ่มไข่มุกเยอะ ๆ',
        total_price: 150,
      },
      {
        id: 'oi-002',
        product_name: 'ข้าวเหนียวมะม่วง',
        product_image: '/placeholder/mango-sticky-rice.jpg',
        product_price: 85,
        quantity: 1,
        options: [],
        item_note: '',
        total_price: 85,
      },
    ],
    subtotal: 235,
    delivery_fee: 0,
    discount: 0,
    total: 235,
    payment_method: 'promptpay',
    payment_status: 'pending',
    payment_slip_url: null,
    delivery_address: {
      label: 'บ้าน',
      address_text: '123/45 คอนโด Life สุขุมวิท 62 ชั้น 15 ห้อง 1512',
      latitude: 13.7058,
      longitude: 100.6014,
      note: 'จอดหน้าล็อบบี้ โทรเมื่อถึง',
    },
    customer_phone: '091-111-2222',
    customer_name: 'วิภา สุขสมบูรณ์',
    scheduled_date: null,
    scheduled_slot: null,
    note: 'ขอช้อนพลาสติกด้วยค่ะ',
    cancel_reason: null,
    driver: null,
    created_at: '2026-02-23T10:30:00Z',
    updated_at: '2026-02-23T10:30:00Z',
  },

  // Order 2 — preparing
  {
    id: 'order-002',
    shop_id: 'shop-001',
    customer_id: 'cust-002',
    driver_id: null,
    order_number: 'OD-20260223-002',
    status: 'preparing',
    items: [
      {
        id: 'oi-003',
        product_name: 'ชานมไข่มุก',
        product_image: '/placeholder/boba-milk-tea.jpg',
        product_price: 55,
        quantity: 1,
        options: [
          { option_id: 'opt-size', option_name: 'ขนาดแก้ว', choice_id: 'size-l', choice_name: 'L (22 oz.)', price_adjustment: 20 },
          { option_id: 'opt-sweet', option_name: 'ระดับความหวาน', choice_id: 'sweet-75', choice_name: 'หวานน้อย (75%)', price_adjustment: 0 },
          { option_id: 'opt-topping', option_name: 'ท็อปปิ้ง', choice_id: 'top-pudding', choice_name: 'พุดดิ้ง', price_adjustment: 15 },
        ],
        item_note: '',
        total_price: 90,
      },
      {
        id: 'oi-004',
        product_name: 'ลาเต้เย็น',
        product_image: '/placeholder/iced-latte.jpg',
        product_price: 65,
        quantity: 1,
        options: [
          { option_id: 'opt-size', option_name: 'ขนาดแก้ว', choice_id: 'size-m', choice_name: 'M (16 oz.)', price_adjustment: 10 },
          { option_id: 'opt-sweet', option_name: 'ระดับความหวาน', choice_id: 'sweet-25', choice_name: 'หวานนิดเดียว (25%)', price_adjustment: 0 },
          { option_id: 'opt-shot', option_name: 'ความเข้มกาแฟ', choice_id: 'shot-double', choice_name: 'เข้ม (2 ช็อต)', price_adjustment: 15 },
          { option_id: 'opt-milk', option_name: 'ชนิดนม', choice_id: 'milk-oat', choice_name: 'นมโอ๊ต', price_adjustment: 15 },
        ],
        item_note: 'ไม่ใส่น้ำแข็งเยอะ',
        total_price: 105,
      },
      {
        id: 'oi-005',
        product_name: 'ครัวซองต์เนยสด',
        product_image: '/placeholder/butter-croissant.jpg',
        product_price: 65,
        quantity: 2,
        options: [],
        item_note: '',
        total_price: 130,
      },
    ],
    subtotal: 325,
    delivery_fee: 20,
    discount: 20,
    total: 325,
    payment_method: 'transfer',
    payment_status: 'paid',
    payment_slip_url: '/placeholder/slip-002.jpg',
    delivery_address: {
      label: 'ออฟฟิศ',
      address_text: '999 อาคาร The PARQ ชั้น 22 ถนนรัชดาภิเษก แขวงคลองเตย',
      latitude: 13.7226,
      longitude: 100.5607,
      note: 'ขึ้นลิฟต์ฝั่ง B',
    },
    customer_phone: '085-333-4444',
    customer_name: 'ธนากร เจริญกิจ',
    scheduled_date: null,
    scheduled_slot: null,
    note: '',
    cancel_reason: null,
    driver: null,
    created_at: '2026-02-23T11:15:00Z',
    updated_at: '2026-02-23T11:20:00Z',
  },

  // Order 3 — delivering
  {
    id: 'order-003',
    shop_id: 'shop-001',
    customer_id: 'cust-003',
    driver_id: 'driver-001',
    order_number: 'OD-20260223-003',
    status: 'delivering',
    items: [
      {
        id: 'oi-006',
        product_name: 'ชานมบราวน์ชูการ์',
        product_image: '/placeholder/brown-sugar-milk-tea.jpg',
        product_price: 65,
        quantity: 3,
        options: [
          { option_id: 'opt-size', option_name: 'ขนาดแก้ว', choice_id: 'size-l', choice_name: 'L (22 oz.)', price_adjustment: 20 },
          { option_id: 'opt-sweet', option_name: 'ระดับความหวาน', choice_id: 'sweet-100', choice_name: 'หวานปกติ (100%)', price_adjustment: 0 },
        ],
        item_note: '',
        total_price: 255,
      },
      {
        id: 'oi-007',
        product_name: 'เค้กชาไทย',
        product_image: '/placeholder/thai-tea-cake.jpg',
        product_price: 75,
        quantity: 1,
        options: [],
        item_note: 'ห่อของขวัญด้วยค่ะ',
        total_price: 75,
      },
    ],
    subtotal: 330,
    delivery_fee: 40,
    discount: 40,
    total: 330,
    payment_method: 'cash',
    payment_status: 'pending',
    payment_slip_url: null,
    delivery_address: {
      label: 'บ้าน',
      address_text: '55/12 หมู่บ้านเพอร์เฟค มาสเตอร์พีซ ซอยอ่อนนุช 44 เขตสวนหลวง',
      latitude: 13.6990,
      longitude: 100.6252,
      note: 'บ้านสีขาว หลังคาเทา ประตูรั้วเหล็กดำ',
    },
    customer_phone: '062-555-6666',
    customer_name: 'ปาริชาต นิมิตรดี',
    scheduled_date: null,
    scheduled_slot: null,
    note: 'โทรก่อนถึง 5 นาที',
    cancel_reason: null,
    driver: {
      id: 'driver-001',
      name: 'สมชาย ใจดี',
      phone: '081-234-5678',
      avatar_url: '/placeholder/driver-somchai.jpg',
      status: 'busy',
      total_deliveries: 1247,
    },
    created_at: '2026-02-23T11:00:00Z',
    updated_at: '2026-02-23T11:35:00Z',
  },
];

// ============================================================
// Mock Promotions
// ============================================================
export const mockPromotions: Promotion[] = [
  // 1. DELIVERY_DISCOUNT — Free delivery over 200 THB
  {
    id: 'promo-001',
    shop_id: 'shop-001',
    name: 'ส่งฟรี! สั่งครบ 200 บาท',
    description: 'สั่งครบ 200 บาทขึ้นไป ฟรีค่าจัดส่ง ไม่ต้องใช้โค้ด',
    promotion_type: 'DELIVERY_DISCOUNT',
    image_url: '/placeholder/promo-free-delivery.jpg',
    is_active: true,
    priority: 1,
    stackable: false,
    auto_apply: true,
    starts_at: '2026-02-01T00:00:00Z',
    ends_at: '2026-03-31T23:59:59Z',
    conditions: {
      min_order_amount: 200,
    },
    actions: {
      discount_type: 'fixed',
      discount_value: 40,
      max_discount: 40,
    },
    limits: {
      max_total_uses: null,
      max_uses_per_customer: null,
      max_uses_per_customer_per_day: 2,
      max_total_budget: null,
      current_spent: 1280,
      max_total_quantity: null,
    },
    codes: [],
    usage_count: 32,
    created_at: '2026-02-01T00:00:00Z',
  },

  // 2. BUY_X_GET_Y — Buy 2 milk tea get 1 free
  {
    id: 'promo-002',
    shop_id: 'shop-001',
    name: 'ซื้อชานม 2 แถม 1',
    description: 'สั่งชานมครบ 2 แก้ว รับฟรีชานมไข่มุกขนาด S 1 แก้ว!',
    promotion_type: 'BUY_X_GET_Y',
    image_url: '/placeholder/promo-buy2get1.jpg',
    is_active: true,
    priority: 2,
    stackable: false,
    auto_apply: false,
    starts_at: '2026-02-15T00:00:00Z',
    ends_at: '2026-02-28T23:59:59Z',
    conditions: {
      category_id: 'cat-milk-tea',
      min_quantity: 2,
    },
    actions: {
      free_product_id: 'prod-007',
      free_product_size: 'size-s',
      free_quantity: 1,
    },
    limits: {
      max_total_uses: 200,
      max_uses_per_customer: 3,
      max_uses_per_customer_per_day: 1,
      max_total_budget: 11000,
      current_spent: 4950,
      max_total_quantity: null,
    },
    codes: [
      { id: 'code-002', code: 'MILK2FREE1', is_active: true, max_uses: 200, used_count: 90 },
    ],
    usage_count: 90,
    created_at: '2026-02-15T00:00:00Z',
  },

  // 3. FLASH_SALE — 30% off matcha drinks (limited time)
  {
    id: 'promo-003',
    shop_id: 'shop-001',
    name: 'Flash Sale! มัทฉะลด 30%',
    description: 'เฉพาะวันนี้ 14:00-16:00 มัทฉะทุกแก้วลด 30%',
    promotion_type: 'FLASH_SALE',
    image_url: '/placeholder/promo-flash-matcha.jpg',
    is_active: true,
    priority: 0,
    stackable: false,
    auto_apply: true,
    starts_at: '2026-02-23T07:00:00Z',
    ends_at: '2026-02-23T09:00:00Z',
    conditions: {
      product_ids: ['prod-001'],
      time_range: { start: '14:00', end: '16:00' },
    },
    actions: {
      discount_type: 'percentage',
      discount_value: 30,
      max_discount: 50,
    },
    limits: {
      max_total_uses: 50,
      max_uses_per_customer: 2,
      max_uses_per_customer_per_day: 2,
      max_total_budget: 2500,
      current_spent: 630,
      max_total_quantity: 50,
    },
    codes: [],
    usage_count: 18,
    created_at: '2026-02-23T00:00:00Z',
  },

  // 4. ORDER_DISCOUNT — 15% off orders over 300 THB
  {
    id: 'promo-004',
    shop_id: 'shop-001',
    name: 'ลด 15% เมื่อสั่ง 300 บาทขึ้นไป',
    description: 'ใส่โค้ด CHACHAK15 รับส่วนลด 15% สูงสุด 80 บาท เมื่อสั่ง 300 บาทขึ้นไป',
    promotion_type: 'ORDER_DISCOUNT',
    image_url: '/placeholder/promo-15off.jpg',
    is_active: true,
    priority: 3,
    stackable: true,
    auto_apply: false,
    starts_at: '2026-02-01T00:00:00Z',
    ends_at: '2026-04-30T23:59:59Z',
    conditions: {
      min_order_amount: 300,
    },
    actions: {
      discount_type: 'percentage',
      discount_value: 15,
      max_discount: 80,
    },
    limits: {
      max_total_uses: 500,
      max_uses_per_customer: 5,
      max_uses_per_customer_per_day: 1,
      max_total_budget: 40000,
      current_spent: 8720,
      max_total_quantity: null,
    },
    codes: [
      { id: 'code-004', code: 'CHACHAK15', is_active: true, max_uses: 500, used_count: 142 },
    ],
    usage_count: 142,
    created_at: '2026-02-01T00:00:00Z',
  },

  // 5. NEW_CUSTOMER — Welcome discount
  {
    id: 'promo-005',
    shop_id: 'shop-001',
    name: 'ลูกค้าใหม่ ลด 50 บาท',
    description: 'ออเดอร์แรกลดทันที 50 บาท ไม่มีขั้นต่ำ สำหรับลูกค้าใหม่เท่านั้น',
    promotion_type: 'NEW_CUSTOMER',
    image_url: '/placeholder/promo-welcome.jpg',
    is_active: true,
    priority: 5,
    stackable: false,
    auto_apply: true,
    starts_at: '2026-01-01T00:00:00Z',
    ends_at: null,
    conditions: {
      is_first_order: true,
    },
    actions: {
      discount_type: 'fixed',
      discount_value: 50,
      max_discount: 50,
    },
    limits: {
      max_total_uses: null,
      max_uses_per_customer: 1,
      max_uses_per_customer_per_day: 1,
      max_total_budget: null,
      current_spent: 3250,
      max_total_quantity: null,
    },
    codes: [
      { id: 'code-005', code: 'WELCOME50', is_active: true, max_uses: null, used_count: 65 },
    ],
    usage_count: 65,
    created_at: '2026-01-01T00:00:00Z',
  },
];

// ============================================================
// Mock Customer Addresses
// ============================================================
export const mockAddresses: CustomerAddress[] = [
  {
    id: 'addr-001',
    label: 'บ้าน',
    address_text: '123/45 คอนโด Life สุขุมวิท 62 ชั้น 15 ห้อง 1512 แขวงบางจาก เขตพระโขนง กรุงเทพฯ 10260',
    latitude: 13.7058,
    longitude: 100.6014,
    note: 'จอดหน้าล็อบบี้ โทรเมื่อถึง',
    is_default: true,
  },
  {
    id: 'addr-002',
    label: 'ออฟฟิศ',
    address_text: '999 อาคาร The PARQ ชั้น 22 ถนนรัชดาภิเษก แขวงคลองเตย เขตคลองเตย กรุงเทพฯ 10110',
    latitude: 13.7226,
    longitude: 100.5607,
    note: 'ขึ้นลิฟต์ฝั่ง B เปิดประตูด้วยบัตร — โทรให้ลงไปรับ',
    is_default: false,
  },
];
